"""add route data to goals and dropbox tokens table

Revision ID: 1e3bdb622ab6
Revises: 54d4f9dcda61
Create Date: 2026-03-15 05:02:52.996491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3bdb622ab6'
down_revision: Union[str, Sequence[str], None] = '54d4f9dcda61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dropbox_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('access_token', sa.String(length=512), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('folder_path', sa.String(length=500), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('goal_events', sa.Column('route_url', sa.String(length=2048), nullable=True))
    op.add_column('goal_events', sa.Column('gpx_file_path', sa.String(length=500), nullable=True))
    op.add_column('goal_events', sa.Column('route_data', sa.JSON(), nullable=True))
    op.alter_column('ride_data', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_foreign_key(None, 'rides', 'workouts', ['workout_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.alter_column('ride_data', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('goal_events', 'route_data')
    op.drop_column('goal_events', 'gpx_file_path')
    op.drop_column('goal_events', 'route_url')
    op.drop_table('dropbox_tokens')
    # ### end Alembic commands ###
