"""initial schema

Revision ID: 54d4f9dcda61
Revises: 
Create Date: 2026-03-14 07:23:43.421839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d4f9dcda61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('ftp', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('experience_level', sa.Enum('beginner', 'intermediate', 'advanced', 'elite', name='experiencelevel'), nullable=True),
    sa.Column('has_power_meter', sa.Boolean(), nullable=False),
    sa.Column('has_smart_trainer', sa.Boolean(), nullable=False),
    sa.Column('has_hr_monitor', sa.Boolean(), nullable=False),
    sa.Column('weekly_hours_available', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('daily_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tss', sa.Float(), nullable=False),
    sa.Column('ctl', sa.Float(), nullable=False),
    sa.Column('atl', sa.Float(), nullable=False),
    sa.Column('tsb', sa.Float(), nullable=False),
    sa.Column('ramp_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_metrics_user_date')
    )
    op.create_index(op.f('ix_daily_metrics_user_id'), 'daily_metrics', ['user_id'], unique=False)
    op.create_table('goal_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.Enum('road_race', 'crit', 'time_trial', 'gran_fondo', 'sportive', 'gravel', 'mtb', name='eventtype'), nullable=False),
    sa.Column('priority', sa.Enum('a_race', 'b_race', 'c_race', name='eventpriority'), nullable=False),
    sa.Column('target_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('primary_goal', sa.Enum('build_fitness', 'target_event', 'improve_ftp', 'race', 'learn_skills', name='primarygoal'), nullable=False),
    sa.Column('secondary_goals', sa.JSON(), nullable=True),
    sa.Column('current_weekly_volume_hours', sa.Float(), nullable=True),
    sa.Column('years_cycling', sa.Integer(), nullable=True),
    sa.Column('indoor_outdoor_preference', sa.Enum('indoor', 'outdoor', 'both', name='indooroutdoorpreference'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('fit_upload', 'strava', 'trainingpeaks', 'manual', 'in_app', name='ridesource'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('ride_date', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('moving_time_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('elevation_gain_meters', sa.Float(), nullable=True),
    sa.Column('average_power', sa.Float(), nullable=True),
    sa.Column('normalized_power', sa.Float(), nullable=True),
    sa.Column('max_power', sa.Integer(), nullable=True),
    sa.Column('average_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('average_cadence', sa.Integer(), nullable=True),
    sa.Column('average_speed', sa.Float(), nullable=True),
    sa.Column('intensity_factor', sa.Float(), nullable=True),
    sa.Column('variability_index', sa.Float(), nullable=True),
    sa.Column('tss', sa.Float(), nullable=True),
    sa.Column('ftp_at_time', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('workout_id', sa.String(length=36), nullable=True),
    sa.Column('fit_file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_rides_ride_date'), 'rides', ['ride_date'], unique=False)
    op.create_index(op.f('ix_rides_user_id'), 'rides', ['user_id'], unique=False)
    op.create_table('strava_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trainingpeaks_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('athlete_id', sa.String(length=100), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='chatrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('ride_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ride_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('cadence', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('left_right_balance', sa.Integer(), nullable=True),
    sa.Column('torque', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ride_data_ride_elapsed', 'ride_data', ['ride_id', 'elapsed_seconds'], unique=False)
    op.create_index(op.f('ix_ride_data_ride_id'), 'ride_data', ['ride_id'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal_event_id', sa.String(length=36), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', 'cancelled', name='planstatus'), nullable=False),
    sa.Column('periodization_model', sa.Enum('traditional', 'polarized', 'sweet_spot', name='periodizationmodel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_event_id'], ['goal_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_user_id'), 'training_plans', ['user_id'], unique=False)
    op.create_table('training_phases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('phase_type', sa.Enum('off_season', 'base', 'build', 'peak', 'race', 'recovery', name='phasetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('target_weekly_tss', sa.Float(), nullable=True),
    sa.Column('target_weekly_hours', sa.Float(), nullable=True),
    sa.Column('focus', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phase_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workout_type', sa.Enum('endurance', 'tempo', 'sweet_spot', 'threshold', 'vo2max', 'sprint', 'recovery', 'rest', name='workouttype'), nullable=False),
    sa.Column('planned_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('planned_tss', sa.Float(), nullable=True),
    sa.Column('planned_if', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'completed', 'skipped', 'modified', name='workoutstatus'), nullable=False),
    sa.Column('actual_ride_id', sa.String(length=36), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actual_ride_id'], ['rides.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['training_phases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_scheduled_date'), 'workouts', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_workouts_user_id'), 'workouts', ['user_id'], unique=False)
    op.create_table('workout_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workout_id', sa.String(length=36), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('warmup', 'steady_state', 'interval_on', 'interval_off', 'cooldown', 'free_ride', 'ramp', name='steptype'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('power_target_pct', sa.Float(), nullable=True),
    sa.Column('power_low_pct', sa.Float(), nullable=True),
    sa.Column('power_high_pct', sa.Float(), nullable=True),
    sa.Column('cadence_target', sa.Integer(), nullable=True),
    sa.Column('repeat_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_steps')
    op.drop_index(op.f('ix_workouts_user_id'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_scheduled_date'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_table('training_phases')
    op.drop_index(op.f('ix_training_plans_user_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_ride_data_ride_id'), table_name='ride_data')
    op.drop_index('ix_ride_data_ride_elapsed', table_name='ride_data')
    op.drop_table('ride_data')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('trainingpeaks_tokens')
    op.drop_table('strava_tokens')
    op.drop_index(op.f('ix_rides_user_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_ride_date'), table_name='rides')
    op.drop_table('rides')
    op.drop_table('onboarding_responses')
    op.drop_table('goal_events')
    op.drop_index(op.f('ix_daily_metrics_user_id'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
