"""widen dropbox token columns to text

Revision ID: 8f88268ad474
Revises: 1e3bdb622ab6
Create Date: 2026-03-15 05:29:44.114093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f88268ad474'
down_revision: Union[str, Sequence[str], None] = '1e3bdb622ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dropbox_tokens', 'access_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('dropbox_tokens', 'refresh_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dropbox_tokens', 'refresh_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('dropbox_tokens', 'access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###
