"""Add training schedule preferences to user

Revision ID: c9ad7200de7c
Revises: f6b4c2d93e51
Create Date: 2026-04-06 06:45:45.748609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9ad7200de7c'
down_revision: Union[str, Sequence[str], None] = 'f6b4c2d93e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal_events', 'status',
               existing_type=postgresql.ENUM('upcoming', 'completed', 'dnf', 'dns', name='goalstatus'),
               nullable=False,
               existing_server_default=sa.text("'upcoming'::goalstatus"))
    op.add_column('users', sa.Column('preferred_hard_days', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('rest_days', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rest_days')
    op.drop_column('users', 'preferred_hard_days')
    op.alter_column('goal_events', 'status',
               existing_type=postgresql.ENUM('upcoming', 'completed', 'dnf', 'dns', name='goalstatus'),
               nullable=True,
               existing_server_default=sa.text("'upcoming'::goalstatus"))
    # ### end Alembic commands ###
