"""Sync DB schema with latest models.py (add normalized_power)

Revision ID: 03bb2c4c4c1f
Revises: 8c1121b48bab
Create Date: 2025-06-08 09:25:38.804022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bb2c4c4c1f'
down_revision: Union[str, None] = '8c1121b48bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
