"""Add normalized_power to rides

Revision ID: 8c1121b48bab
Revises: 
Create Date: 2025-06-08 08:49:37.701809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1121b48bab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('avg_power', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('avg_cadence', sa.Float(), nullable=True),
    sa.Column('max_power', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('max_cadence', sa.Float(), nullable=True),
    sa.Column('total_work_kj', sa.Float(), nullable=True),
    sa.Column('tss', sa.Float(), nullable=True),
    sa.Column('normalized_power', sa.Float(), nullable=True),
    sa.Column('left_right_balance', sa.String(), nullable=True),
    sa.Column('power_zone_times', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rides_id'), 'rides', ['id'], unique=False)
    op.create_index(op.f('ix_rides_ride_id'), 'rides', ['ride_id'], unique=True)
    op.drop_index(op.f('ix_time_in_zone_id'), table_name='time_in_zone')
    op.drop_table('time_in_zone')
    op.drop_index(op.f('ix_ride_data_id'), table_name='ride_data')
    op.drop_index(op.f('ix_ride_data_timestamp'), table_name='ride_data')
    op.drop_table('ride_data')
    op.drop_index(op.f('ix_hr_time_in_zone_id'), table_name='hr_time_in_zone')
    op.drop_table('hr_time_in_zone')
    op.drop_index(op.f('ix_ftp_records_id'), table_name='ftp_records')
    op.drop_table('ftp_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ftp_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ftp', sa.FLOAT(), nullable=True),
    sa.Column('date_set', sa.DATETIME(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ftp_records_id'), 'ftp_records', ['id'], unique=False)
    op.create_table('hr_time_in_zone',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('zone', sa.VARCHAR(), nullable=True),
    sa.Column('seconds', sa.INTEGER(), nullable=True),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_time_in_zone_id'), 'hr_time_in_zone', ['id'], unique=False)
    op.create_table('ride_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('power', sa.FLOAT(), nullable=True),
    sa.Column('heart_rate', sa.FLOAT(), nullable=True),
    sa.Column('cadence', sa.FLOAT(), nullable=True),
    sa.Column('speed', sa.FLOAT(), nullable=True),
    sa.Column('distance', sa.FLOAT(), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_data_timestamp'), 'ride_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ride_data_id'), 'ride_data', ['id'], unique=False)
    op.create_table('time_in_zone',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('zone', sa.VARCHAR(), nullable=True),
    sa.Column('seconds', sa.INTEGER(), nullable=True),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_in_zone_id'), 'time_in_zone', ['id'], unique=False)
    op.drop_index(op.f('ix_rides_ride_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_id'), table_name='rides')
    op.drop_table('rides')
    # ### end Alembic commands ###
