"""Add normalized_power to rides table

Revision ID: dbe549e3bee3
Revises: 
Create Date: 2025-06-08 14:39:31.275706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbe549e3bee3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('normalized_power', sa.Float(), nullable=True))
    op.alter_column('rides', 'ride_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('rides', 'left_right_balance',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('rides', 'power_zone_times',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_ride_id'), table_name='rides')
    op.drop_constraint(op.f('rides_ride_id_key'), 'rides', type_='unique')
    op.create_index(op.f('ix_rides_ride_id'), 'rides', ['ride_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rides_ride_id'), table_name='rides')
    op.create_unique_constraint(op.f('rides_ride_id_key'), 'rides', ['ride_id'])
    op.create_index(op.f('idx_ride_id'), 'rides', ['ride_id'], unique=False)
    op.alter_column('rides', 'power_zone_times',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rides', 'left_right_balance',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('rides', 'ride_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('rides', 'normalized_power')
    # ### end Alembic commands ###
